Repository codestates-seb/seb45_main_016, pull requests merged in 2023-09, with the labels that each got.

#56 FEAT: CI/CI를 위한 파일 추가 및 구축
  .github/workflows/deploy.yml
  server/.github/workflows/deploy.yml
  server/appspec.yml
  server/scripts/start.sh
  server/scripts/stop.sh
Labels: documentation, backend, 인수

#57 feat: Spring Security jwt 기능 추가
  server/build.gradle
  server/src/main/java/com/codestates/server/domain/member/dto/MemberLoginResponseDto.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/codestates/server/domain/member/entity/Member.java
  server/src/main/java/com/codestates/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/global/security/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/global/security/auth/dto/LoginDto.java
  server/src/main/java/com/codestates/server/global/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/global/security/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/global/security/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/codestates/server/global/security/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/server/global/security/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/global/security/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/server/global/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/global/security/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/codestates/server/global/security/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/global/security/response/ErrorResponder.java
  server/src/main/java/com/codestates/server/global/security/response/ErrorResponse.java
  server/src/main/resources/application.yml
Labels: backend, 솔이

#61 feat : board entity 일부 구성
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb45_main_016.iml
  .idea/vcs.xml
  server/src/main/java/com/codestates/server/domain/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPostDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/Response.java
  server/src/main/java/com/codestates/server/domain/board/entity/Board.java
  server/src/main/java/com/codestates/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/domain/board/service/BoardService.java
  server/src/main/java/com/codestates/server/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
Labels: documentation, backend, 건국

#82 feat: 스프링 배치 구현
  server/build.gradle
  server/src/main/java/com/codestates/server/ServerApplication.java
  server/src/main/java/com/codestates/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codestates/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codestates/server/domain/license/dto/CsvDto.java
  server/src/main/java/com/codestates/server/domain/license/dto/LicenseDto.java
  server/src/main/java/com/codestates/server/domain/license/entity/License.java
  server/src/main/java/com/codestates/server/domain/license/repository/LicenseRepository.java
  server/src/main/java/com/codestates/server/domain/license/service/LicenseService.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchConfig.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchScheduler.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseProcessor.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseReader.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseWriter.java
  server/src/main/java/com/codestates/server/global/batch/infra/JsonParser.java
  server/src/main/java/com/codestates/server/global/batch/infra/LicenseApi.java
  server/src/main/java/com/codestates/server/global/batch/mapper/CsvToCsvDtoMapper.java
  server/src/main/java/com/codestates/server/global/batch/mapper/LicenseToLicenseDtoMapper.java
  server/src/main/resources/application.yml
  server/src/main/resources/csv/license.csv
  server/src/test/java/com/codestates/server/domain/batch/LicenseApiTest.java
Labels: backend, 해영

#62 FEAT: 예외처리 추가 및 예외메세지 추가
  server/.github/workflows/deploy.yml
  server/appspec.yml
  server/scripts/start.sh
  server/scripts/stop.sh
  server/src/main/java/com/codestates/server/global/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/server/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/server/global/security/response/ErrorResponse.java
Labels: documentation, backend, 인수

#104 design:MainPage 세부디자인적용
  client/package-lock.json
  client/package.json
  client/public/Main.png
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderStyle.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/MainStyle.js
Labels: frontend, 현아

#107 feat: security OAuth2 라이브러리 없이 카카오 기능 추가하기
  .github/workflows/deploy.yml
  server/build.gradle
  server/src/main/java/com/codestates/server/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/domain/member/entity/Member.java
  server/src/main/java/com/codestates/server/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/global/security/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/global/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/global/security/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/global/security/oauth2/config/KakaoOAuthConfig.java
  server/src/main/java/com/codestates/server/global/security/oauth2/controller/KakaoOAuthController.java
  server/src/main/java/com/codestates/server/global/security/oauth2/dto/KakaoMemberInfoDto.java
  server/src/main/java/com/codestates/server/global/security/oauth2/service/KakaoOAuthService.java
  server/src/main/java/com/codestates/server/global/security/oauth2/v2/attribute/CustomOAuth2User.java
  server/src/main/java/com/codestates/server/global/security/oauth2/v2/attribute/OAuth2Attribute.java
  server/src/main/java/com/codestates/server/global/security/oauth2/v2/handler/OAuth2FailureHandler.java
  server/src/main/java/com/codestates/server/global/security/oauth2/v2/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/codestates/server/global/security/oauth2/v2/service/CustomOAuth2UserService.java
  server/src/main/resources/application.yml
Labels: backend, 솔이

#114 FEAT : 댓글(Answer) 구현
  server/src/main/java/com/codestates/server/domain/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/server/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/domain/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/domain/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/domain/answer/service/AnswerService.java
Labels: documentation, backend, 건국

#116 fix: license list
  client/src/components/LicenseCard/LicenseCard.js
  client/src/components/Modal/Modal.js
  client/src/components/Modal/ModalStyle.js
  client/src/pages/Community/ComDetailMock.js
  client/src/pages/Community/ComDetailStyle.js
  client/src/pages/LicenseInfo/Info.js
  client/src/pages/LicenseInfo/infoDummydata.js
Labels: frontend, 선혜

#122 [BE] License, Bookmark, Board, Answer 구현
  server/gradlew.bat
  server/src/main/java/com/codestates/server/domain/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerBoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/domain/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/domain/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/domain/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPageResponse.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPostDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/board/entity/Board.java
  server/src/main/java/com/codestates/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/domain/board/service/BoardService.java
  server/src/main/java/com/codestates/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codestates/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/codestates/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/com/codestates/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codestates/server/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/codestates/server/domain/license/controller/LicenseController.java
  server/src/main/java/com/codestates/server/domain/license/dto/LicenseDto.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/dto/LicenseDto.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/dto/LicenseResponseDto.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/entity/LicenseDate.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/mapper/LicenseDateMapper.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/repository/LicenseDateRepository.java
  server/src/main/java/com/codestates/server/domain/license/licenseinfo/dto/CsvDto.java
  server/src/main/java/com/codestates/server/domain/license/licenseinfo/entity/LicenseInfo.java
  server/src/main/java/com/codestates/server/domain/license/licenseinfo/repository/LicenseInfoRepository.java
  server/src/main/java/com/codestates/server/domain/license/repository/LicenseRepository.java
  server/src/main/java/com/codestates/server/domain/license/service/LicenseService.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberBoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/member/entity/Member.java
  server/src/main/java/com/codestates/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchConfig.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchScheduler.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseProcessor.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseReader.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseWriter.java
  server/src/main/java/com/codestates/server/global/batch/infra/JsonParser.java
  server/src/main/java/com/codestates/server/global/batch/infra/LicenseApi.java
  server/src/main/java/com/codestates/server/global/batch/mapper/CsvToCsvDtoMapper.java
  server/src/main/java/com/codestates/server/global/uri/UriCreator.java
  server/src/main/resources/application.yml
  server/src/main/resources/database/data.sql
  server/src/test/java/com/codestates/server/domain/batch/LicenseDateApiTest.java
Labels: backend, 해영

#115 feat: 프로필 이미지 추가 기능 구현
  server/build.gradle
  server/src/main/java/com/codestates/server/ServerApplication.java
  server/src/main/java/com/codestates/server/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberImagePatchDto.java
  server/src/main/java/com/codestates/server/domain/member/entity/AuthUserUtils.java
  server/src/main/java/com/codestates/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/domain/member/s3/S3Config.java
  server/src/main/java/com/codestates/server/domain/member/s3/S3UploadService.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/global/security/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/global/security/oauth2/controller/KakaoOAuthController.java
  server/src/main/resources/application.yml
Labels: backend, 솔이

#113 FEAT: 대댓글 CRUD 구현
  server/src/main/java/com/codestates/server/domain/reply/controller/ReplyController.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyPatchDto.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyPostDto.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/codestates/server/domain/reply/entity/Reply.java
  server/src/main/java/com/codestates/server/domain/reply/mapper/ReplyMapper.java
  server/src/main/java/com/codestates/server/domain/reply/repository/ReplyRepository.java
  server/src/main/java/com/codestates/server/domain/reply/service/ReplyService.java
  server/src/main/java/com/codestates/server/global/exception/ExceptionCode.java
Labels: documentation, backend, 인수

#125 feat: search
  client/src/App.js
  client/src/components/Bookmark/BookmarkStyle.js
  client/src/components/LicenseCard/LicenseCardStyle.js
  client/src/components/Modal/Modal.js
  client/src/pages/Community/ComDetailMock.js
  client/src/pages/Community/PostContent.js
  client/src/pages/Filtered/SearchFiltered.js
  client/src/pages/Filtered/dummy.js
  client/src/utils/API.js
Labels: frontend, 선혜

#126 design:detail design
  client/src/components/DelModal/DelModal.js
  client/src/components/DelModal/DelModalStyle.js
  client/src/pages/Filtered/FilteredStyle.js
  client/src/pages/Filtered/SearchFiltered.js
  client/src/pages/LicenseInfo/InfoStyle.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/MainStyle.js
  client/src/pages/Mypage/MyInfo.js
  client/src/pages/Mypage/MypageStyle.js
  client/src/utils/API.js
Labels: frontend, 현아

#128 [BE] comment - bookmark - member - answer 구현 및 예외처리
  README.md
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerBoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/domain/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardPostDto.java
  server/src/main/java/com/codestates/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/codestates/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codestates/server/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/codestates/server/domain/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/domain/comment/dto/CommentAnswerDto.java
  server/src/main/java/com/codestates/server/domain/comment/dto/CommentPatchDto.java
  server/src/main/java/com/codestates/server/domain/comment/dto/CommentPostDto.java
  server/src/main/java/com/codestates/server/domain/comment/entity/Comment.java
  server/src/main/java/com/codestates/server/domain/comment/mapper/CommentMapper.java
  server/src/main/java/com/codestates/server/domain/comment/repository/CommentRepository.java
  server/src/main/java/com/codestates/server/domain/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/domain/license/controller/LicenseController.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/dto/LicenseGetDto.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/dto/LicenseResponseDto.java
  server/src/main/java/com/codestates/server/domain/license/licensedate/mapper/LicenseDateMapper.java
  server/src/main/java/com/codestates/server/domain/license/service/LicenseService.java
  server/src/main/java/com/codestates/server/domain/reply/controller/ReplyController.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyPatchDto.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyPostDto.java
  server/src/main/java/com/codestates/server/domain/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/codestates/server/domain/reply/entity/Reply.java
  server/src/main/java/com/codestates/server/domain/reply/mapper/ReplyMapper.java
  server/src/main/java/com/codestates/server/domain/reply/repository/ReplyRepository.java
  server/src/main/java/com/codestates/server/domain/reply/service/ReplyService.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchConfig.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseProcessor.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseReader.java
  server/src/main/java/com/codestates/server/global/batch/config/LicenseWriter.java
  server/src/main/java/com/codestates/server/global/batch/infra/JsonParser.java
  server/src/main/java/com/codestates/server/global/batch/infra/LicenseApi.java
  server/src/main/java/com/codestates/server/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/global/security/auth/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
Labels: backend, 해영

#134 Dev front
  client/src/App.js
  client/src/components/404/404notfound.js
  client/src/components/Bookmark/Bookmark.js
  client/src/components/Header/Header.js
  client/src/components/comment/Comment.js
  client/src/components/comment/Reply.js
  client/src/components/comment/style.js
  client/src/pages/Community/ComDetail.js
  client/src/pages/Community/ComDetailMock.js
  client/src/pages/Community/ComList.js
  client/src/pages/Community/ComListMock.js
  client/src/pages/Filtered/SearchFiltered.js
  client/src/pages/Signup/SignUp.js
  client/src/pages/Signup/SignUpStyle.js
  client/src/utils/API.js
Labels: frontend, 선혜

#135 fix: test코드 삭제
  server/src/main/java/com/codestates/server/domain/license/controller/LicenseController.java
  server/src/main/java/com/codestates/server/domain/license/service/LicenseService.java
  server/src/main/java/com/codestates/server/global/batch/infra/LicenseApi.java
Labels: backend, 해영

#142 feat: community- board, answer, comment crud
  client/public/index.html
  client/src/App.js
  client/src/components/Bookmark/Bookmark.js
  client/src/components/Header/Header.js
  client/src/components/Modal/Modal.js
  client/src/index.js
  client/src/pages/Community/AnswerForm.js
  client/src/pages/Community/AnswerList.js
  client/src/pages/Community/ComData.js
  client/src/pages/Community/ComDetail.js
  client/src/pages/Community/ComDetailStyle.js
  client/src/pages/Community/ComList.js
  client/src/pages/Community/CreateAnswer.js
  client/src/pages/LicenseInfo/Info.js
  client/src/pages/LicenseInfo/InfoStyle.js
  client/src/pages/Main/Main.js
  client/src/utils/API.js
  client/src/utils/ComData.js
Labels: frontend, 선혜

#143 [BE] feat: 이메일 알림 기능 추가 (가입 알림 + 시험 알림) / 이메일 검증 로직 추가
  server/build.gradle
  server/src/main/generated/com/codestates/server/domain/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/com/codestates/server/domain/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/codestates/server/domain/license/licensedate/mapper/LicenseDateMapperImpl.java
  server/src/main/generated/com/codestates/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/codestates/server/global/batch/mapper/LicenseToLicenseDtoMapperImpl.java
  server/src/main/java/com/codestates/server/ServerApplication.java
  server/src/main/java/com/codestates/server/domain/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/domain/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/domain/board/service/BoardService.java
  server/src/main/java/com/codestates/server/domain/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/domain/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/domain/license/licenseinfo/entity/LicenseInfo.java
  server/src/main/java/com/codestates/server/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/codestates/server/domain/member/entity/Member.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/global/mail/event/MemberRegistrationEvent.java
  server/src/main/java/com/codestates/server/global/mail/sevice/EmailService.java
  server/src/main/java/com/codestates/server/global/mail/sevice/LicenseNotificationService.java
  server/src/main/java/com/codestates/server/global/mail/sevice/MemberRegistrationService.java
  server/src/main/java/com/codestates/server/global/mail/sevice/NotificationService.java
  server/src/main/java/com/codestates/server/global/security/auth/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/global/security/utils/AuthUserUtils.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/doc-announcement-template.html
  server/src/main/resources/templates/doc-exam-template.html
  server/src/main/resources/templates/doc-registration-template.html
  server/src/main/resources/templates/prac-announcement-template.html
  server/src/main/resources/templates/prac-exam-template.html
  server/src/main/resources/templates/prac-registration-template.html
  server/src/main/resources/templates/welcome-template.html
Labels: backend, 솔이

#154 fix: 리팩터링
  server/src/main/java/com/codestates/server/domain/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/domain/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/domain/license/controller/LicenseController.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/domain/search/controller/SearchController.java
Labels: backend, 해영

#168 [BE] 에러 수정
  server/src/main/generated/com/codestates/server/domain/board/mapper/BoardMapperImpl.java
  server/src/main/java/com/codestates/server/domain/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/domain/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/domain/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/domain/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/domain/board/service/BoardService.java
  server/src/main/java/com/codestates/server/domain/license/controller/LicenseController.java
  server/src/main/java/com/codestates/server/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/server/global/batch/config/BatchConfig.java
  server/src/main/java/com/codestates/server/global/batch/infra/JsonParser.java
  server/src/main/java/com/codestates/server/global/batch/infra/LicenseApi.java
  server/src/main/resources/application.yml
Labels: backend, 해영
